### ISSUE TITLE
make faf-java-api deploy init.lua

### ISSUE THREAD

**Issue by shalkya** [micheljung/faf-java-api#413] opened 2020-08-25 12:13 UTC
so that we can update the init.lua in the game.
It is actually quite important, numerous of fixes are on pause because of this, ie mappers can't use custom prop to make maps etc...
see : https://github.com/FAForever/fa/pull/3109

**Comment by Brutus5000** [comment] 2020-08-25 12:15
Duplicate of #406

**Closed as completed by Brutus5000** 2020-08-25 12:15 UTC
Labels: enhancement
