### ISSUE TITLE
uploading mod packs

### ISSUE THREAD

**Issue by PhilipJFryFAF** [micheljung/faf-java-api#298] opened 2019-01-03 20:49 UTC
When uploading a mod pack (a folder with a mod_info.lua + an icon with several mods in sub directories) then the api will pick up the first mod_info.lua file it can find

It would be nice if the mod_info.lua that is being used to showcase the mod in the vault would be picked from the root folder (the java client needs it to be there anyway so you literally cannot upload a mod without a mod_info.lua in the root folder of the mod)

**Comment by Brutus5000** [comment] 2019-01-03 20:54
The issue is probably in java commons here: https://github.com/FAForever/faf-java-commons/blob/develop/faf-commons-data/src/main/java/com/faforever/commons/mod/ModReader.java#L54

We only look first for the mod_info.lua not checking that it is in the root directory. For mod packs this might lead to the wrong mod_info.lua being picked up.

**Comment by basalt79** [comment] 2021-10-21 19:06
@Brutus5000  can you give me some more details whats the actual problem, current vs expected behavior. (example zips) ? 

`
├── No Friendly Fire
│   ├── hook
│   │   └── lua
│   │       └── sim
│   │           └── Unit.lua
│   ├── mod_icon.png
│   └── mod_info.lua

`

**Comment by Brutus5000** [comment] 2021-10-21 20:05
Unfortunately I have no example zip of such a problem, although I could fake one.
A regular mod file structure looks as you described above.

A **mod pack** however is a nested folder with multiple mods of the structure above together in one root directory which itself has yet another mod_info.lua on root level that holds everything together.


The problem is now (as far as I can tell) that we iterate through the zip file and take the first mod_info.lua (because we only expected one when writing the code) and did not check if it is in the top level folder. However the zip file gives no guarantee which files appear first, so it could be one of the nested mod_info.lua files.

Does that help you?

**Comment by basalt79** [comment] 2021-10-21 20:38
ok i got it, if it is ok, i would give it a try

**Comment by basalt79** [comment] 2021-10-21 21:47
@Brutus5000  do you want to transfer or recreate a issue at https://github.com/FAForever/faf-java-commons project? Or should I create the PR without any issue linking?

**Comment by Brutus5000** [comment] 2021-10-21 23:21
Create the PR without issue please.

**Comment by basalt79** [comment] 2021-10-22 05:01
@Brutus5000 if you like it, i would be happy to get the `hacktoberfest-accepted` label on the PR

**Comment by Brutus5000** [comment] 2021-10-22 05:30
@basalt79 I merged it straight away. That should also count towards hacktoberfest, if not ping me again.

Also if you want to "finish" this issue with another PR you'll need to make the faf-java-commons dependency https://github.com/FAForever/faf-java-api/blob/baa940a58bc02baedb4620722043d9927a3571c3/gradle.properties#L20 point to the new commit id (0e5d22ffff6e4dea81bac494d532627fcca8ebc4)

**Comment by basalt79** [comment] 2021-10-22 05:36
sure, i will finish it

**Comment by Brutus5000** [comment] 2021-10-22 06:19
Should be fixed in next release

**Closed as completed by Brutus5000** 2021-10-22 06:19 UTC
Labels: good first issue
