### ISSUE TITLE
Internal Server error on request

### ISSUE THREAD

**Issue by 1-alex98** [micheljung/faf-java-api#383] opened 2020-03-28 00:46 UTC
The following request throws 500

https://api.faforever.com/data/game?sort=-endTime&filter=playerStats.player.login==Explosive&include=mapVersion,mapVersion.map&fields[game]=mapVersion&fields[mapVersion]=map, thumbnailUrlLarge&fields[map]=displayName&page[limit]=10000

**Comment by bukajsytlos** [comment] 2020-03-28 21:10
works on my machine :), @Brutus5000  logs?

**Comment by Brutus5000** [comment] 2020-03-28 22:00
This is caused by https://github.com/FAForever/db/issues/215

**Comment by Brutus5000** [comment] 2020-03-28 22:05
I'm closing this as nothing in the API can (or should) prevent this error.

**Closed as completed by Brutus5000** 2020-03-28 22:05 UTC

**Comment by Brutus5000** [comment] 2020-04-17 21:07
Query works now by the way.
